version: '3'

services:
  net-control:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
       - /etc/hosts:/etc/hosts
    network_mode: "host"
    env_file: 
      config.env
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    privileged: true